"""renamed Venue.seeking_venue to Venu.seeking_talent

Revision ID: 79c0c7f1a204
Revises: 6f512f3a45ee
Create Date: 2020-12-19 17:51:58.781323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c0c7f1a204'
down_revision = '6f512f3a45ee'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
	op.execute('UPDATE "Venue" SET seeking_talent=seeking_venue')
	op.alter_column('Venue', 'seeking_talent', nullable=False)
	op.drop_column('Venue', 'seeking_venue')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('Venue', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
	op.drop_column('Venue', 'seeking_talent')
	# ### end Alembic commands ###
